### PR TITLE
Remove 'Register' button

### PR DESCRIPTION
**Pull request by ntdkhiem**
- 'Go To Dashboard' serves the same functionality.

### CODE REVIEW

**Comment by ntdkhiem** [comment]
This PR is intended to fix #129 .

**Review by vjawahar — COMMENTED** [review]
Flip the change so it removes the "Go to Dashboard" button and keeps the "Register" button since that is more clear.

**Review by AVS1508 — COMMENTED** [review]
The change has been flipped while resolving the merge conflict with `main`. The 'Go to Dashboard' button has been removed in favor of the 'Register' button as requested.

**Review by vjawahar — COMMENTED** [review]
lgtm

**Review by vjawahar — APPROVED** [review]
LGTM

**Pull request merged**
